apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backend
  namespace: production
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: backend-job
        spec:
          containers:
          - name: backend-job
            image: openstatefoundation/open-raadsinformatie-backend
            imagePullPolicy: Always
            command: ["python"]
            args: |-
              - manage.py
              - extract
              - start
              - notubiz
            envFrom:
            - configMapRef:
                name: config
            volumeMounts:
            - mountPath: /opt/ori/data
              name: oridata
          securityContext:
            runAsUser: 1000
            fsGroup: 1000
          volumes:
          - name: oridata
            persistentVolumeClaim:
              claimName: oridata
          restartPolicy: OnFailure
