apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: openstatefoundation/open-raadsinformatie-frontend
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - mountPath: /opt/ori/static
          name: oridata
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
      - name: oridata
        persistentVolumeClaim:
          claimName: oridata
