apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: production
spec:
  selector:
    app: neo4j
  type: ClusterIP
  ports:
  - name: "browser"
    port: 7474
    targetPort: 7474
  - name: "data"
    port: 7687
    targetPort: 7687
